name: test action workflow form api
on:
  repository_dispatch:
    types: [incident_reported]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run test action workflow form api
        run: echo "test action workflow form api is running"