name: Learn GitHub Actions
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: test workflows
        run: echo "test workflow"

      - name: check repo
        uses: actions/checkout@v6

      - name: listing files
        run: ls -la